languageCode = "en"
languageName = "English"
weight = 1
title = "Agustín Ferrari Braun"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Personal academic website of Agustín Ferrari Braun"
[params.author]
  name = "Agustín Ferrari Braun"
  email = "a.l.ferrraribraun@uva.nl"
  
  bio = "I study the semiotic implications of things that mean other things. My current project investigates whether laundry instructions constitute a form of oppressive discourse. I have opinions about Derrida that I will share with you whether you asked or not."
  links = [
    { bluesky = "https://bsky.app/profile/ferraribraun.bsky.social" },
    { email = "mailto:a.l.ferrraribraun@uva.nl" },
    { linkedin = "https://www.linkedin.com/in/agustin-ferrari-braun-a5a005130/"},
  ]
  image = "img/2504_AlgoSoc_Paper.jpg"
  